/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GlobalNote {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'category' : string,
  'attachedPublisher' : [] | [PublisherId],
}
export interface Publisher {
  'id' : PublisherId,
  'privileges' : {
    'servant' : boolean,
    'publisher' : boolean,
    'elder' : boolean,
  },
  'fieldServiceGroup' : bigint,
  'fullName' : string,
  'isGroupOverseer' : boolean,
  'isActive' : boolean,
  'isGroupAssistant' : boolean,
}
export type PublisherId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPublisher' : ActorMethod<
    [
      string,
      bigint,
      { 'servant' : boolean, 'publisher' : boolean, 'elder' : boolean },
      boolean,
      boolean,
      [] | [boolean],
    ],
    PublisherId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGlobalNote' : ActorMethod<
    [string, string, string, [] | [PublisherId]],
    bigint
  >,
  'deleteGlobalNote' : ActorMethod<[bigint], undefined>,
  'deletePublisher' : ActorMethod<[PublisherId], undefined>,
  'getAllGlobalNotes' : ActorMethod<[], Array<GlobalNote>>,
  'getAllPublishers' : ActorMethod<[], Array<Publisher>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalNote' : ActorMethod<[bigint], [] | [GlobalNote]>,
  'getPublisher' : ActorMethod<[PublisherId], [] | [Publisher]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'togglePublisherActiveState' : ActorMethod<[PublisherId], undefined>,
  'updateGlobalNote' : ActorMethod<
    [bigint, string, string, string, [] | [PublisherId]],
    undefined
  >,
  'updatePublisher' : ActorMethod<
    [
      PublisherId,
      string,
      bigint,
      { 'servant' : boolean, 'publisher' : boolean, 'elder' : boolean },
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];