/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddGroupVisitInput = IDL.Record({
  'groupNumber' : IDL.Nat,
  'notesForOverseer' : IDL.Text,
  'notesForAssistant' : IDL.Text,
  'visitDate' : IDL.Int,
  'publisherNamesPresent' : IDL.Vec(IDL.Text),
  'publishersPresent' : IDL.Vec(IDL.Text),
  'discussionTopics' : IDL.Text,
  'nextPlannedVisitDate' : IDL.Opt(IDL.Int),
});
export const CreatePioneerMonthlyHoursInput = IDL.Record({
  'month' : IDL.Text,
  'serviceYear' : IDL.Text,
  'hours' : IDL.Nat,
  'pioneerId' : IDL.Text,
});
export const PublisherId = IDL.Nat;
export const CreateTrainedConductorInput = IDL.Record({
  'status' : IDL.Text,
  'availableSaturday' : IDL.Opt(IDL.Bool),
  'availableThursday' : IDL.Opt(IDL.Bool),
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'trainingDate' : IDL.Int,
  'availableSunday' : IDL.Opt(IDL.Bool),
  'availableFriday' : IDL.Opt(IDL.Bool),
});
export const CreateTrainedPublisherInput = IDL.Record({
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'trainingDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreatePioneerInput = IDL.Record({
  'serviceYear' : IDL.Text,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
});
export const CreateShepherdingVisitInput = IDL.Record({
  'eldersPresent' : IDL.Text,
  'visitDate' : IDL.Int,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'notes' : IDL.Text,
});
export const CreateTaskInput = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : IDL.Int,
  'parentTaskId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const CreateTerritoryNoteInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const EditPioneerInput = IDL.Record({
  'serviceYear' : IDL.Text,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
});
export const GlobalNote = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'category' : IDL.Text,
  'attachedPublisher' : IDL.Opt(PublisherId),
});
export const GroupVisit = IDL.Record({
  'id' : IDL.Text,
  'groupNumber' : IDL.Nat,
  'notesForOverseer' : IDL.Text,
  'notesForAssistant' : IDL.Text,
  'createdAt' : IDL.Int,
  'visitDate' : IDL.Int,
  'publisherNamesPresent' : IDL.Vec(IDL.Text),
  'publishersPresent' : IDL.Vec(IDL.Text),
  'discussionTopics' : IDL.Text,
  'nextPlannedVisitDate' : IDL.Opt(IDL.Int),
});
export const Pioneer = IDL.Record({
  'id' : IDL.Text,
  'serviceYear' : IDL.Text,
  'createdAt' : IDL.Int,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Publisher = IDL.Record({
  'id' : PublisherId,
  'privileges' : IDL.Record({
    'servant' : IDL.Bool,
    'publisher' : IDL.Bool,
    'elder' : IDL.Bool,
  }),
  'fieldServiceGroup' : IDL.Nat,
  'fullName' : IDL.Text,
  'isGroupOverseer' : IDL.Bool,
  'isActive' : IDL.Bool,
  'isGroupAssistant' : IDL.Bool,
});
export const ServiceMeetingConductor = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'conductorName' : IDL.Text,
  'conductorId' : IDL.Text,
  'weekOf' : IDL.Int,
});
export const ShepherdingVisit = IDL.Record({
  'id' : IDL.Text,
  'eldersPresent' : IDL.Text,
  'createdAt' : IDL.Int,
  'visitDate' : IDL.Int,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'notes' : IDL.Text,
});
export const CheckoutRecord = IDL.Record({
  'publisherId' : PublisherId,
  'publisherName' : IDL.Text,
  'dateReturned' : IDL.Opt(IDL.Int),
  'isCampaign' : IDL.Bool,
  'dateCheckedOut' : IDL.Int,
});
export const Territory = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'checkOutHistory' : IDL.Vec(CheckoutRecord),
  'territoryType' : IDL.Text,
  'notes' : IDL.Text,
  'number' : IDL.Text,
});
export const TerritoryNote = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const TrainedServiceMeetingConductor = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'availableSaturday' : IDL.Bool,
  'availableThursday' : IDL.Bool,
  'createdAt' : IDL.Int,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'trainingDate' : IDL.Int,
  'availableSunday' : IDL.Bool,
  'availableFriday' : IDL.Bool,
});
export const TrainedPublisher = IDL.Record({
  'id' : IDL.Text,
  'isAuthorized' : IDL.Bool,
  'createdAt' : IDL.Int,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'hasS148Received' : IDL.Bool,
  'trainingDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'congregationName' : IDL.Text,
});
export const PioneerMonthlyHours = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Text,
  'serviceYear' : IDL.Text,
  'hours' : IDL.Nat,
  'pioneerId' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Opt(IDL.Int),
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'updatedAt' : IDL.Opt(IDL.Int),
  'parentTaskId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'all' : IDL.Null,
  'completed' : IDL.Null,
  'uncompleted' : IDL.Null,
});
export const UpdateTrainedConductorInput = IDL.Record({
  'status' : IDL.Text,
  'availableSaturday' : IDL.Opt(IDL.Bool),
  'availableThursday' : IDL.Opt(IDL.Bool),
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'trainingDate' : IDL.Int,
  'availableSunday' : IDL.Opt(IDL.Bool),
  'availableFriday' : IDL.Opt(IDL.Bool),
});
export const UpdateTrainedPublisherInput = IDL.Record({
  'isAuthorized' : IDL.Bool,
  'publisherId' : IDL.Text,
  'publisherName' : IDL.Text,
  'trainingDate' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGroupVisit' : IDL.Func([AddGroupVisitInput], [IDL.Text], []),
  'addPioneerHours' : IDL.Func(
      [CreatePioneerMonthlyHoursInput],
      [IDL.Text],
      [],
    ),
  'addPublisher' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Record({
          'servant' : IDL.Bool,
          'publisher' : IDL.Bool,
          'elder' : IDL.Bool,
        }),
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Bool),
      ],
      [PublisherId],
      [],
    ),
  'addTrainedConductor' : IDL.Func(
      [CreateTrainedConductorInput],
      [IDL.Text],
      [],
    ),
  'addTrainedPublisher' : IDL.Func(
      [CreateTrainedPublisherInput],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkOutTerritory' : IDL.Func([IDL.Text, PublisherId, IDL.Bool], [], []),
  'createGlobalNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
      [IDL.Nat],
      [],
    ),
  'createPioneer' : IDL.Func([CreatePioneerInput], [IDL.Text], []),
  'createShepherdingVisit' : IDL.Func(
      [CreateShepherdingVisitInput],
      [IDL.Text],
      [],
    ),
  'createTask' : IDL.Func([CreateTaskInput], [IDL.Nat], []),
  'createTerritory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createTerritoryNote' : IDL.Func(
      [IDL.Text, CreateTerritoryNoteInput],
      [IDL.Nat],
      [],
    ),
  'deleteCheckoutRecord' : IDL.Func([IDL.Text, PublisherId, IDL.Int], [], []),
  'deleteGlobalNote' : IDL.Func([IDL.Nat], [], []),
  'deleteGroupVisit' : IDL.Func([IDL.Text], [], []),
  'deletePioneer' : IDL.Func([IDL.Text], [], []),
  'deletePioneerHours' : IDL.Func([IDL.Text], [], []),
  'deletePublisher' : IDL.Func([PublisherId], [], []),
  'deleteShepherdingVisit' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTerritory' : IDL.Func([IDL.Text], [], []),
  'deleteTerritoryNote' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteTrainedConductor' : IDL.Func([IDL.Text], [], []),
  'deleteTrainedPublisher' : IDL.Func([IDL.Text], [], []),
  'editPioneer' : IDL.Func([IDL.Text, EditPioneerInput], [], []),
  'getAllGlobalNotes' : IDL.Func([], [IDL.Vec(GlobalNote)], ['query']),
  'getAllGroupVisits' : IDL.Func([], [IDL.Vec(GroupVisit)], ['query']),
  'getAllPioneers' : IDL.Func([], [IDL.Vec(Pioneer)], ['query']),
  'getAllPublishers' : IDL.Func([], [IDL.Vec(Publisher)], ['query']),
  'getAllServiceMeetingConductors' : IDL.Func(
      [],
      [IDL.Vec(ServiceMeetingConductor)],
      ['query'],
    ),
  'getAllShepherdingVisits' : IDL.Func(
      [],
      [IDL.Vec(ShepherdingVisit)],
      ['query'],
    ),
  'getAllTerritories' : IDL.Func([], [IDL.Vec(Territory)], ['query']),
  'getAllTerritoryNotes' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TerritoryNote)],
      ['query'],
    ),
  'getAllTrainedConductors' : IDL.Func(
      [],
      [IDL.Vec(TrainedServiceMeetingConductor)],
      ['query'],
    ),
  'getAllTrainedPublishers' : IDL.Func(
      [],
      [IDL.Vec(TrainedPublisher)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalNote' : IDL.Func([IDL.Nat], [IDL.Opt(GlobalNote)], ['query']),
  'getGroupVisit' : IDL.Func([IDL.Text], [IDL.Opt(GroupVisit)], ['query']),
  'getGroupVisitsByGroupNumber' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GroupVisit)],
      ['query'],
    ),
  'getGroupVisitsForGroup' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GroupVisit)],
      ['query'],
    ),
  'getPioneer' : IDL.Func([IDL.Text], [IDL.Opt(Pioneer)], ['query']),
  'getPioneerHours' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PioneerMonthlyHours)],
      ['query'],
    ),
  'getPioneerHoursForServiceYear' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PioneerMonthlyHours)],
      ['query'],
    ),
  'getPublisher' : IDL.Func([PublisherId], [IDL.Opt(Publisher)], ['query']),
  'getPublishers' : IDL.Func([], [IDL.Vec(Publisher)], ['query']),
  'getShepherdingVisit' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ShepherdingVisit)],
      ['query'],
    ),
  'getShepherdingVisitsByPublisher' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShepherdingVisit)],
      ['query'],
    ),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTasks' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
  'getTasksByParent' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Task)], ['query']),
  'getTerritory' : IDL.Func([IDL.Text], [IDL.Opt(Territory)], ['query']),
  'getTerritoryNote' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(TerritoryNote)],
      ['query'],
    ),
  'getTrainedConductor' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrainedServiceMeetingConductor)],
      ['query'],
    ),
  'getTrainedConductorProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrainedServiceMeetingConductor)],
      ['query'],
    ),
  'getTrainedPublisher' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrainedPublisher)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeTerritoryAvailable' : IDL.Func([IDL.Text], [], []),
  'markTerritoryReturned' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setS148Received' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'togglePublisherActiveState' : IDL.Func([PublisherId], [], []),
  'updateCheckoutRecord' : IDL.Func(
      [
        IDL.Text,
        PublisherId,
        IDL.Int,
        PublisherId,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateGlobalNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
      [],
      [],
    ),
  'updateGroupVisit' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'updatePioneerHours' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updatePublisher' : IDL.Func(
      [
        PublisherId,
        IDL.Text,
        IDL.Nat,
        IDL.Record({
          'servant' : IDL.Bool,
          'publisher' : IDL.Bool,
          'elder' : IDL.Bool,
        }),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateShepherdingVisit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTask' : IDL.Func([IDL.Nat, CreateTaskInput], [], []),
  'updateTaskCompletion' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateTerritory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTerritoryNote' : IDL.Func(
      [IDL.Text, IDL.Nat, CreateTerritoryNoteInput],
      [],
      [],
    ),
  'updateTrainedConductor' : IDL.Func(
      [IDL.Text, UpdateTrainedConductorInput],
      [],
      [],
    ),
  'updateTrainedPublisher' : IDL.Func(
      [IDL.Text, UpdateTrainedPublisherInput],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddGroupVisitInput = IDL.Record({
    'groupNumber' : IDL.Nat,
    'notesForOverseer' : IDL.Text,
    'notesForAssistant' : IDL.Text,
    'visitDate' : IDL.Int,
    'publisherNamesPresent' : IDL.Vec(IDL.Text),
    'publishersPresent' : IDL.Vec(IDL.Text),
    'discussionTopics' : IDL.Text,
    'nextPlannedVisitDate' : IDL.Opt(IDL.Int),
  });
  const CreatePioneerMonthlyHoursInput = IDL.Record({
    'month' : IDL.Text,
    'serviceYear' : IDL.Text,
    'hours' : IDL.Nat,
    'pioneerId' : IDL.Text,
  });
  const PublisherId = IDL.Nat;
  const CreateTrainedConductorInput = IDL.Record({
    'status' : IDL.Text,
    'availableSaturday' : IDL.Opt(IDL.Bool),
    'availableThursday' : IDL.Opt(IDL.Bool),
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'trainingDate' : IDL.Int,
    'availableSunday' : IDL.Opt(IDL.Bool),
    'availableFriday' : IDL.Opt(IDL.Bool),
  });
  const CreateTrainedPublisherInput = IDL.Record({
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'trainingDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreatePioneerInput = IDL.Record({
    'serviceYear' : IDL.Text,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
  });
  const CreateShepherdingVisitInput = IDL.Record({
    'eldersPresent' : IDL.Text,
    'visitDate' : IDL.Int,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'notes' : IDL.Text,
  });
  const CreateTaskInput = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : IDL.Int,
    'parentTaskId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const CreateTerritoryNoteInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const EditPioneerInput = IDL.Record({
    'serviceYear' : IDL.Text,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
  });
  const GlobalNote = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'category' : IDL.Text,
    'attachedPublisher' : IDL.Opt(PublisherId),
  });
  const GroupVisit = IDL.Record({
    'id' : IDL.Text,
    'groupNumber' : IDL.Nat,
    'notesForOverseer' : IDL.Text,
    'notesForAssistant' : IDL.Text,
    'createdAt' : IDL.Int,
    'visitDate' : IDL.Int,
    'publisherNamesPresent' : IDL.Vec(IDL.Text),
    'publishersPresent' : IDL.Vec(IDL.Text),
    'discussionTopics' : IDL.Text,
    'nextPlannedVisitDate' : IDL.Opt(IDL.Int),
  });
  const Pioneer = IDL.Record({
    'id' : IDL.Text,
    'serviceYear' : IDL.Text,
    'createdAt' : IDL.Int,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Publisher = IDL.Record({
    'id' : PublisherId,
    'privileges' : IDL.Record({
      'servant' : IDL.Bool,
      'publisher' : IDL.Bool,
      'elder' : IDL.Bool,
    }),
    'fieldServiceGroup' : IDL.Nat,
    'fullName' : IDL.Text,
    'isGroupOverseer' : IDL.Bool,
    'isActive' : IDL.Bool,
    'isGroupAssistant' : IDL.Bool,
  });
  const ServiceMeetingConductor = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'conductorName' : IDL.Text,
    'conductorId' : IDL.Text,
    'weekOf' : IDL.Int,
  });
  const ShepherdingVisit = IDL.Record({
    'id' : IDL.Text,
    'eldersPresent' : IDL.Text,
    'createdAt' : IDL.Int,
    'visitDate' : IDL.Int,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'notes' : IDL.Text,
  });
  const CheckoutRecord = IDL.Record({
    'publisherId' : PublisherId,
    'publisherName' : IDL.Text,
    'dateReturned' : IDL.Opt(IDL.Int),
    'isCampaign' : IDL.Bool,
    'dateCheckedOut' : IDL.Int,
  });
  const Territory = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'checkOutHistory' : IDL.Vec(CheckoutRecord),
    'territoryType' : IDL.Text,
    'notes' : IDL.Text,
    'number' : IDL.Text,
  });
  const TerritoryNote = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const TrainedServiceMeetingConductor = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'availableSaturday' : IDL.Bool,
    'availableThursday' : IDL.Bool,
    'createdAt' : IDL.Int,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'trainingDate' : IDL.Int,
    'availableSunday' : IDL.Bool,
    'availableFriday' : IDL.Bool,
  });
  const TrainedPublisher = IDL.Record({
    'id' : IDL.Text,
    'isAuthorized' : IDL.Bool,
    'createdAt' : IDL.Int,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'hasS148Received' : IDL.Bool,
    'trainingDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'congregationName' : IDL.Text,
  });
  const PioneerMonthlyHours = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Text,
    'serviceYear' : IDL.Text,
    'hours' : IDL.Nat,
    'pioneerId' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Opt(IDL.Int),
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'updatedAt' : IDL.Opt(IDL.Int),
    'parentTaskId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'all' : IDL.Null,
    'completed' : IDL.Null,
    'uncompleted' : IDL.Null,
  });
  const UpdateTrainedConductorInput = IDL.Record({
    'status' : IDL.Text,
    'availableSaturday' : IDL.Opt(IDL.Bool),
    'availableThursday' : IDL.Opt(IDL.Bool),
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'trainingDate' : IDL.Int,
    'availableSunday' : IDL.Opt(IDL.Bool),
    'availableFriday' : IDL.Opt(IDL.Bool),
  });
  const UpdateTrainedPublisherInput = IDL.Record({
    'isAuthorized' : IDL.Bool,
    'publisherId' : IDL.Text,
    'publisherName' : IDL.Text,
    'trainingDate' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGroupVisit' : IDL.Func([AddGroupVisitInput], [IDL.Text], []),
    'addPioneerHours' : IDL.Func(
        [CreatePioneerMonthlyHoursInput],
        [IDL.Text],
        [],
      ),
    'addPublisher' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Record({
            'servant' : IDL.Bool,
            'publisher' : IDL.Bool,
            'elder' : IDL.Bool,
          }),
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Bool),
        ],
        [PublisherId],
        [],
      ),
    'addTrainedConductor' : IDL.Func(
        [CreateTrainedConductorInput],
        [IDL.Text],
        [],
      ),
    'addTrainedPublisher' : IDL.Func(
        [CreateTrainedPublisherInput],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkOutTerritory' : IDL.Func([IDL.Text, PublisherId, IDL.Bool], [], []),
    'createGlobalNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
        [IDL.Nat],
        [],
      ),
    'createPioneer' : IDL.Func([CreatePioneerInput], [IDL.Text], []),
    'createShepherdingVisit' : IDL.Func(
        [CreateShepherdingVisitInput],
        [IDL.Text],
        [],
      ),
    'createTask' : IDL.Func([CreateTaskInput], [IDL.Nat], []),
    'createTerritory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createTerritoryNote' : IDL.Func(
        [IDL.Text, CreateTerritoryNoteInput],
        [IDL.Nat],
        [],
      ),
    'deleteCheckoutRecord' : IDL.Func([IDL.Text, PublisherId, IDL.Int], [], []),
    'deleteGlobalNote' : IDL.Func([IDL.Nat], [], []),
    'deleteGroupVisit' : IDL.Func([IDL.Text], [], []),
    'deletePioneer' : IDL.Func([IDL.Text], [], []),
    'deletePioneerHours' : IDL.Func([IDL.Text], [], []),
    'deletePublisher' : IDL.Func([PublisherId], [], []),
    'deleteShepherdingVisit' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTerritory' : IDL.Func([IDL.Text], [], []),
    'deleteTerritoryNote' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteTrainedConductor' : IDL.Func([IDL.Text], [], []),
    'deleteTrainedPublisher' : IDL.Func([IDL.Text], [], []),
    'editPioneer' : IDL.Func([IDL.Text, EditPioneerInput], [], []),
    'getAllGlobalNotes' : IDL.Func([], [IDL.Vec(GlobalNote)], ['query']),
    'getAllGroupVisits' : IDL.Func([], [IDL.Vec(GroupVisit)], ['query']),
    'getAllPioneers' : IDL.Func([], [IDL.Vec(Pioneer)], ['query']),
    'getAllPublishers' : IDL.Func([], [IDL.Vec(Publisher)], ['query']),
    'getAllServiceMeetingConductors' : IDL.Func(
        [],
        [IDL.Vec(ServiceMeetingConductor)],
        ['query'],
      ),
    'getAllShepherdingVisits' : IDL.Func(
        [],
        [IDL.Vec(ShepherdingVisit)],
        ['query'],
      ),
    'getAllTerritories' : IDL.Func([], [IDL.Vec(Territory)], ['query']),
    'getAllTerritoryNotes' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TerritoryNote)],
        ['query'],
      ),
    'getAllTrainedConductors' : IDL.Func(
        [],
        [IDL.Vec(TrainedServiceMeetingConductor)],
        ['query'],
      ),
    'getAllTrainedPublishers' : IDL.Func(
        [],
        [IDL.Vec(TrainedPublisher)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalNote' : IDL.Func([IDL.Nat], [IDL.Opt(GlobalNote)], ['query']),
    'getGroupVisit' : IDL.Func([IDL.Text], [IDL.Opt(GroupVisit)], ['query']),
    'getGroupVisitsByGroupNumber' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GroupVisit)],
        ['query'],
      ),
    'getGroupVisitsForGroup' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GroupVisit)],
        ['query'],
      ),
    'getPioneer' : IDL.Func([IDL.Text], [IDL.Opt(Pioneer)], ['query']),
    'getPioneerHours' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PioneerMonthlyHours)],
        ['query'],
      ),
    'getPioneerHoursForServiceYear' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PioneerMonthlyHours)],
        ['query'],
      ),
    'getPublisher' : IDL.Func([PublisherId], [IDL.Opt(Publisher)], ['query']),
    'getPublishers' : IDL.Func([], [IDL.Vec(Publisher)], ['query']),
    'getShepherdingVisit' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ShepherdingVisit)],
        ['query'],
      ),
    'getShepherdingVisitsByPublisher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShepherdingVisit)],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTasks' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
    'getTasksByParent' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getTerritory' : IDL.Func([IDL.Text], [IDL.Opt(Territory)], ['query']),
    'getTerritoryNote' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(TerritoryNote)],
        ['query'],
      ),
    'getTrainedConductor' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrainedServiceMeetingConductor)],
        ['query'],
      ),
    'getTrainedConductorProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrainedServiceMeetingConductor)],
        ['query'],
      ),
    'getTrainedPublisher' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrainedPublisher)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeTerritoryAvailable' : IDL.Func([IDL.Text], [], []),
    'markTerritoryReturned' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setS148Received' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'togglePublisherActiveState' : IDL.Func([PublisherId], [], []),
    'updateCheckoutRecord' : IDL.Func(
        [
          IDL.Text,
          PublisherId,
          IDL.Int,
          PublisherId,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateGlobalNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
        [],
        [],
      ),
    'updateGroupVisit' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'updatePioneerHours' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updatePublisher' : IDL.Func(
        [
          PublisherId,
          IDL.Text,
          IDL.Nat,
          IDL.Record({
            'servant' : IDL.Bool,
            'publisher' : IDL.Bool,
            'elder' : IDL.Bool,
          }),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateShepherdingVisit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTask' : IDL.Func([IDL.Nat, CreateTaskInput], [], []),
    'updateTaskCompletion' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateTerritory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTerritoryNote' : IDL.Func(
        [IDL.Text, IDL.Nat, CreateTerritoryNoteInput],
        [],
        [],
      ),
    'updateTrainedConductor' : IDL.Func(
        [IDL.Text, UpdateTrainedConductorInput],
        [],
        [],
      ),
    'updateTrainedPublisher' : IDL.Func(
        [IDL.Text, UpdateTrainedPublisherInput],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };