/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PublisherId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GlobalNote = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'category' : IDL.Text,
  'attachedPublisher' : IDL.Opt(PublisherId),
});
export const Publisher = IDL.Record({
  'id' : PublisherId,
  'privileges' : IDL.Record({
    'servant' : IDL.Bool,
    'publisher' : IDL.Bool,
    'elder' : IDL.Bool,
  }),
  'fieldServiceGroup' : IDL.Nat,
  'fullName' : IDL.Text,
  'isGroupOverseer' : IDL.Bool,
  'isActive' : IDL.Bool,
  'isGroupAssistant' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPublisher' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Record({
          'servant' : IDL.Bool,
          'publisher' : IDL.Bool,
          'elder' : IDL.Bool,
        }),
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Bool),
      ],
      [PublisherId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGlobalNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
      [IDL.Nat],
      [],
    ),
  'deleteGlobalNote' : IDL.Func([IDL.Nat], [], []),
  'deletePublisher' : IDL.Func([PublisherId], [], []),
  'getAllGlobalNotes' : IDL.Func([], [IDL.Vec(GlobalNote)], ['query']),
  'getAllPublishers' : IDL.Func([], [IDL.Vec(Publisher)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalNote' : IDL.Func([IDL.Nat], [IDL.Opt(GlobalNote)], ['query']),
  'getPublisher' : IDL.Func([PublisherId], [IDL.Opt(Publisher)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'togglePublisherActiveState' : IDL.Func([PublisherId], [], []),
  'updateGlobalNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
      [],
      [],
    ),
  'updatePublisher' : IDL.Func(
      [
        PublisherId,
        IDL.Text,
        IDL.Nat,
        IDL.Record({
          'servant' : IDL.Bool,
          'publisher' : IDL.Bool,
          'elder' : IDL.Bool,
        }),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PublisherId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GlobalNote = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'category' : IDL.Text,
    'attachedPublisher' : IDL.Opt(PublisherId),
  });
  const Publisher = IDL.Record({
    'id' : PublisherId,
    'privileges' : IDL.Record({
      'servant' : IDL.Bool,
      'publisher' : IDL.Bool,
      'elder' : IDL.Bool,
    }),
    'fieldServiceGroup' : IDL.Nat,
    'fullName' : IDL.Text,
    'isGroupOverseer' : IDL.Bool,
    'isActive' : IDL.Bool,
    'isGroupAssistant' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPublisher' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Record({
            'servant' : IDL.Bool,
            'publisher' : IDL.Bool,
            'elder' : IDL.Bool,
          }),
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Bool),
        ],
        [PublisherId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGlobalNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
        [IDL.Nat],
        [],
      ),
    'deleteGlobalNote' : IDL.Func([IDL.Nat], [], []),
    'deletePublisher' : IDL.Func([PublisherId], [], []),
    'getAllGlobalNotes' : IDL.Func([], [IDL.Vec(GlobalNote)], ['query']),
    'getAllPublishers' : IDL.Func([], [IDL.Vec(Publisher)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalNote' : IDL.Func([IDL.Nat], [IDL.Opt(GlobalNote)], ['query']),
    'getPublisher' : IDL.Func([PublisherId], [IDL.Opt(Publisher)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'togglePublisherActiveState' : IDL.Func([PublisherId], [], []),
    'updateGlobalNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PublisherId)],
        [],
        [],
      ),
    'updatePublisher' : IDL.Func(
        [
          PublisherId,
          IDL.Text,
          IDL.Nat,
          IDL.Record({
            'servant' : IDL.Bool,
            'publisher' : IDL.Bool,
            'elder' : IDL.Bool,
          }),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };