/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddGroupVisitInput {
  'groupNumber' : bigint,
  'notesForOverseer' : string,
  'notesForAssistant' : string,
  'visitDate' : bigint,
  'publisherNamesPresent' : Array<string>,
  'publishersPresent' : Array<string>,
  'discussionTopics' : string,
  'nextPlannedVisitDate' : [] | [bigint],
}
export interface CheckoutRecord {
  'publisherId' : PublisherId,
  'publisherName' : string,
  'dateReturned' : [] | [bigint],
  'isCampaign' : boolean,
  'dateCheckedOut' : bigint,
}
export interface CreatePioneerInput {
  'serviceYear' : string,
  'publisherId' : string,
  'publisherName' : string,
}
export interface CreatePioneerMonthlyHoursInput {
  'month' : string,
  'serviceYear' : string,
  'hours' : bigint,
  'pioneerId' : string,
}
export interface CreateShepherdingVisitInput {
  'eldersPresent' : string,
  'visitDate' : bigint,
  'publisherId' : string,
  'publisherName' : string,
  'notes' : string,
}
export interface CreateTaskInput {
  'title' : string,
  'dueDate' : bigint,
  'parentTaskId' : [] | [bigint],
  'notes' : [] | [string],
  'category' : string,
}
export interface CreateTerritoryNoteInput {
  'title' : string,
  'content' : string,
}
export interface CreateTrainedConductorInput {
  'status' : string,
  'availableSaturday' : [] | [boolean],
  'availableThursday' : [] | [boolean],
  'publisherId' : string,
  'publisherName' : string,
  'notes' : [] | [string],
  'trainingDate' : bigint,
  'availableSunday' : [] | [boolean],
  'availableFriday' : [] | [boolean],
}
export interface CreateTrainedPublisherInput {
  'publisherId' : string,
  'publisherName' : string,
  'trainingDate' : bigint,
}
export interface EditPioneerInput {
  'serviceYear' : string,
  'publisherId' : string,
  'publisherName' : string,
}
export interface GlobalNote {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'category' : string,
  'attachedPublisher' : [] | [PublisherId],
}
export interface GroupVisit {
  'id' : string,
  'groupNumber' : bigint,
  'notesForOverseer' : string,
  'notesForAssistant' : string,
  'createdAt' : bigint,
  'visitDate' : bigint,
  'publisherNamesPresent' : Array<string>,
  'publishersPresent' : Array<string>,
  'discussionTopics' : string,
  'nextPlannedVisitDate' : [] | [bigint],
}
export interface Pioneer {
  'id' : string,
  'serviceYear' : string,
  'createdAt' : bigint,
  'publisherId' : string,
  'publisherName' : string,
  'isActive' : boolean,
}
export interface PioneerMonthlyHours {
  'id' : string,
  'month' : string,
  'serviceYear' : string,
  'hours' : bigint,
  'pioneerId' : string,
  'createdAt' : bigint,
}
export interface Publisher {
  'id' : PublisherId,
  'privileges' : {
    'servant' : boolean,
    'publisher' : boolean,
    'elder' : boolean,
  },
  'fieldServiceGroup' : bigint,
  'fullName' : string,
  'isGroupOverseer' : boolean,
  'isActive' : boolean,
  'isGroupAssistant' : boolean,
}
export type PublisherId = bigint;
export interface ServiceMeetingConductor {
  'id' : string,
  'createdAt' : bigint,
  'conductorName' : string,
  'conductorId' : string,
  'weekOf' : bigint,
}
export interface ShepherdingVisit {
  'id' : string,
  'eldersPresent' : string,
  'createdAt' : bigint,
  'visitDate' : bigint,
  'publisherId' : string,
  'publisherName' : string,
  'notes' : string,
}
export interface Task {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'title' : string,
  'isCompleted' : boolean,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'updatedAt' : [] | [bigint],
  'parentTaskId' : [] | [bigint],
  'notes' : [] | [string],
  'category' : string,
}
export type TaskStatus = { 'all' : null } |
  { 'completed' : null } |
  { 'uncompleted' : null };
export interface Territory {
  'id' : string,
  'status' : string,
  'createdAt' : bigint,
  'checkOutHistory' : Array<CheckoutRecord>,
  'territoryType' : string,
  'notes' : string,
  'number' : string,
}
export interface TerritoryNote {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface TrainedPublisher {
  'id' : string,
  'isAuthorized' : boolean,
  'createdAt' : bigint,
  'publisherId' : string,
  'publisherName' : string,
  'hasS148Received' : boolean,
  'trainingDate' : bigint,
}
export interface TrainedServiceMeetingConductor {
  'id' : string,
  'status' : string,
  'availableSaturday' : boolean,
  'availableThursday' : boolean,
  'createdAt' : bigint,
  'publisherId' : string,
  'publisherName' : string,
  'notes' : [] | [string],
  'trainingDate' : bigint,
  'availableSunday' : boolean,
  'availableFriday' : boolean,
}
export interface UpdateTrainedConductorInput {
  'status' : string,
  'availableSaturday' : [] | [boolean],
  'availableThursday' : [] | [boolean],
  'publisherId' : string,
  'publisherName' : string,
  'notes' : [] | [string],
  'trainingDate' : bigint,
  'availableSunday' : [] | [boolean],
  'availableFriday' : [] | [boolean],
}
export interface UpdateTrainedPublisherInput {
  'isAuthorized' : boolean,
  'publisherId' : string,
  'publisherName' : string,
  'trainingDate' : bigint,
}
export interface UserProfile { 'name' : string, 'congregationName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGroupVisit' : ActorMethod<[AddGroupVisitInput], string>,
  'addPioneerHours' : ActorMethod<[CreatePioneerMonthlyHoursInput], string>,
  'addPublisher' : ActorMethod<
    [
      string,
      bigint,
      { 'servant' : boolean, 'publisher' : boolean, 'elder' : boolean },
      boolean,
      boolean,
      [] | [boolean],
    ],
    PublisherId
  >,
  'addTrainedConductor' : ActorMethod<[CreateTrainedConductorInput], string>,
  'addTrainedPublisher' : ActorMethod<[CreateTrainedPublisherInput], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOutTerritory' : ActorMethod<[string, PublisherId, boolean], undefined>,
  'createGlobalNote' : ActorMethod<
    [string, string, string, [] | [PublisherId]],
    bigint
  >,
  'createPioneer' : ActorMethod<[CreatePioneerInput], string>,
  'createShepherdingVisit' : ActorMethod<[CreateShepherdingVisitInput], string>,
  'createTask' : ActorMethod<[CreateTaskInput], bigint>,
  'createTerritory' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    string
  >,
  'createTerritoryNote' : ActorMethod<
    [string, CreateTerritoryNoteInput],
    bigint
  >,
  'deleteCheckoutRecord' : ActorMethod<
    [string, PublisherId, bigint],
    undefined
  >,
  'deleteGlobalNote' : ActorMethod<[bigint], undefined>,
  'deleteGroupVisit' : ActorMethod<[string], undefined>,
  'deletePioneer' : ActorMethod<[string], undefined>,
  'deletePioneerHours' : ActorMethod<[string], undefined>,
  'deletePublisher' : ActorMethod<[PublisherId], undefined>,
  'deleteShepherdingVisit' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTerritory' : ActorMethod<[string], undefined>,
  'deleteTerritoryNote' : ActorMethod<[string, bigint], undefined>,
  'deleteTrainedConductor' : ActorMethod<[string], undefined>,
  'deleteTrainedPublisher' : ActorMethod<[string], undefined>,
  'editPioneer' : ActorMethod<[string, EditPioneerInput], undefined>,
  'getAllGlobalNotes' : ActorMethod<[], Array<GlobalNote>>,
  'getAllGroupVisits' : ActorMethod<[], Array<GroupVisit>>,
  'getAllPioneers' : ActorMethod<[], Array<Pioneer>>,
  'getAllPublishers' : ActorMethod<[], Array<Publisher>>,
  'getAllServiceMeetingConductors' : ActorMethod<
    [],
    Array<ServiceMeetingConductor>
  >,
  'getAllShepherdingVisits' : ActorMethod<[], Array<ShepherdingVisit>>,
  'getAllTerritories' : ActorMethod<[], Array<Territory>>,
  'getAllTerritoryNotes' : ActorMethod<[string], Array<TerritoryNote>>,
  'getAllTrainedConductors' : ActorMethod<
    [],
    Array<TrainedServiceMeetingConductor>
  >,
  'getAllTrainedPublishers' : ActorMethod<[], Array<TrainedPublisher>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalNote' : ActorMethod<[bigint], [] | [GlobalNote]>,
  'getGroupVisit' : ActorMethod<[string], [] | [GroupVisit]>,
  'getGroupVisitsByGroupNumber' : ActorMethod<[bigint], Array<GroupVisit>>,
  'getGroupVisitsForGroup' : ActorMethod<[bigint], Array<GroupVisit>>,
  'getPioneer' : ActorMethod<[string], [] | [Pioneer]>,
  'getPioneerHours' : ActorMethod<[string], [] | [PioneerMonthlyHours]>,
  'getPioneerHoursForServiceYear' : ActorMethod<
    [string, string],
    Array<PioneerMonthlyHours>
  >,
  'getPublisher' : ActorMethod<[PublisherId], [] | [Publisher]>,
  'getPublishers' : ActorMethod<[], Array<Publisher>>,
  'getShepherdingVisit' : ActorMethod<[string], [] | [ShepherdingVisit]>,
  'getShepherdingVisitsByPublisher' : ActorMethod<
    [string],
    Array<ShepherdingVisit>
  >,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTasks' : ActorMethod<[TaskStatus], Array<Task>>,
  'getTasksByParent' : ActorMethod<[[] | [bigint]], Array<Task>>,
  'getTerritory' : ActorMethod<[string], [] | [Territory]>,
  'getTerritoryNote' : ActorMethod<[string, bigint], [] | [TerritoryNote]>,
  'getTrainedConductor' : ActorMethod<
    [string],
    [] | [TrainedServiceMeetingConductor]
  >,
  'getTrainedConductorProfile' : ActorMethod<
    [string],
    [] | [TrainedServiceMeetingConductor]
  >,
  'getTrainedPublisher' : ActorMethod<[string], [] | [TrainedPublisher]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeTerritoryAvailable' : ActorMethod<[string], undefined>,
  'markTerritoryReturned' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setS148Received' : ActorMethod<[string, boolean], undefined>,
  'togglePublisherActiveState' : ActorMethod<[PublisherId], undefined>,
  'updateCheckoutRecord' : ActorMethod<
    [string, PublisherId, bigint, PublisherId, bigint, [] | [bigint], boolean],
    undefined
  >,
  'updateGlobalNote' : ActorMethod<
    [bigint, string, string, string, [] | [PublisherId]],
    undefined
  >,
  'updateGroupVisit' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      [] | [bigint],
    ],
    undefined
  >,
  'updatePioneerHours' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'updatePublisher' : ActorMethod<
    [
      PublisherId,
      string,
      bigint,
      { 'servant' : boolean, 'publisher' : boolean, 'elder' : boolean },
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
  'updateShepherdingVisit' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
  'updateTask' : ActorMethod<[bigint, CreateTaskInput], undefined>,
  'updateTaskCompletion' : ActorMethod<[bigint, boolean], undefined>,
  'updateTerritory' : ActorMethod<[string, string, string], undefined>,
  'updateTerritoryNote' : ActorMethod<
    [string, bigint, CreateTerritoryNoteInput],
    undefined
  >,
  'updateTrainedConductor' : ActorMethod<
    [string, UpdateTrainedConductorInput],
    undefined
  >,
  'updateTrainedPublisher' : ActorMethod<
    [string, UpdateTrainedPublisherInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];