/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckoutRecord {
  'publisherId' : PublisherId,
  'publisherName' : string,
  'dateReturned' : [] | [bigint],
  'isCampaign' : boolean,
  'dateCheckedOut' : bigint,
}
export interface CreateTaskInput {
  'title' : string,
  'dueDate' : bigint,
  'parentTaskId' : [] | [bigint],
  'notes' : [] | [string],
  'category' : string,
}
export interface CreateTerritoryNoteInput {
  'title' : string,
  'content' : string,
}
export interface GlobalNote {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'category' : string,
  'attachedPublisher' : [] | [PublisherId],
}
export interface Publisher {
  'id' : PublisherId,
  'privileges' : {
    'servant' : boolean,
    'publisher' : boolean,
    'elder' : boolean,
  },
  'fieldServiceGroup' : bigint,
  'fullName' : string,
  'isGroupOverseer' : boolean,
  'isActive' : boolean,
  'isGroupAssistant' : boolean,
}
export type PublisherId = bigint;
export interface Task {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'title' : string,
  'isCompleted' : boolean,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'updatedAt' : [] | [bigint],
  'parentTaskId' : [] | [bigint],
  'notes' : [] | [string],
  'category' : string,
}
export type TaskStatus = { 'all' : null } |
  { 'completed' : null } |
  { 'uncompleted' : null };
export interface Territory {
  'id' : string,
  'status' : string,
  'createdAt' : bigint,
  'checkOutHistory' : Array<CheckoutRecord>,
  'territoryType' : string,
  'notes' : string,
  'number' : string,
}
export interface TerritoryNote {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPublisher' : ActorMethod<
    [
      string,
      bigint,
      { 'servant' : boolean, 'publisher' : boolean, 'elder' : boolean },
      boolean,
      boolean,
      [] | [boolean],
    ],
    PublisherId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOutTerritory' : ActorMethod<[string, PublisherId, boolean], undefined>,
  'createGlobalNote' : ActorMethod<
    [string, string, string, [] | [PublisherId]],
    bigint
  >,
  'createTask' : ActorMethod<[CreateTaskInput], bigint>,
  'createTerritory' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    string
  >,
  'createTerritoryNote' : ActorMethod<
    [string, CreateTerritoryNoteInput],
    bigint
  >,
  'deleteGlobalNote' : ActorMethod<[bigint], undefined>,
  'deletePublisher' : ActorMethod<[PublisherId], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTerritory' : ActorMethod<[string], undefined>,
  'deleteTerritoryNote' : ActorMethod<[string, bigint], undefined>,
  'getAllGlobalNotes' : ActorMethod<[], Array<GlobalNote>>,
  'getAllPublishers' : ActorMethod<[], Array<Publisher>>,
  'getAllTerritories' : ActorMethod<[], Array<Territory>>,
  'getAllTerritoryNotes' : ActorMethod<[string], Array<TerritoryNote>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalNote' : ActorMethod<[bigint], [] | [GlobalNote]>,
  'getPublisher' : ActorMethod<[PublisherId], [] | [Publisher]>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTasks' : ActorMethod<[TaskStatus], Array<Task>>,
  'getTasksByParent' : ActorMethod<[[] | [bigint]], Array<Task>>,
  'getTerritory' : ActorMethod<[string], [] | [Territory]>,
  'getTerritoryNote' : ActorMethod<[string, bigint], [] | [TerritoryNote]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeTerritoryAvailable' : ActorMethod<[string], undefined>,
  'markTerritoryReturned' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'togglePublisherActiveState' : ActorMethod<[PublisherId], undefined>,
  'updateGlobalNote' : ActorMethod<
    [bigint, string, string, string, [] | [PublisherId]],
    undefined
  >,
  'updatePublisher' : ActorMethod<
    [
      PublisherId,
      string,
      bigint,
      { 'servant' : boolean, 'publisher' : boolean, 'elder' : boolean },
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
  'updateTask' : ActorMethod<[bigint, CreateTaskInput], undefined>,
  'updateTaskCompletion' : ActorMethod<[bigint, boolean], undefined>,
  'updateTerritory' : ActorMethod<[string, string, string], undefined>,
  'updateTerritoryNote' : ActorMethod<
    [string, bigint, CreateTerritoryNoteInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];