/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateTrainedConductorInput {
    status: string;
    publisherId: string;
    publisherName: string;
    trainingDate: bigint;
}
export interface ShepherdingVisit {
    id: string;
    eldersPresent: string;
    createdAt: bigint;
    visitDate: bigint;
    publisherId: string;
    publisherName: string;
    notes: string;
}
export type PublisherId = bigint;
export interface CreateTaskInput {
    title: string;
    dueDate: bigint;
    parentTaskId?: bigint;
    notes?: string;
    category: string;
}
export interface Task {
    id: bigint;
    completedAt?: bigint;
    title: string;
    isCompleted: boolean;
    createdAt: bigint;
    dueDate: bigint;
    updatedAt?: bigint;
    parentTaskId?: bigint;
    notes?: string;
    category: string;
}
export interface ServiceMeetingConductor {
    id: string;
    createdAt: bigint;
    conductorName: string;
    conductorId: string;
    weekOf: bigint;
}
export interface GlobalNote {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    category: string;
    attachedPublisher?: PublisherId;
}
export interface EditPioneerInput {
    serviceYear: string;
    publisherId: string;
    publisherName: string;
}
export interface Pioneer {
    id: string;
    serviceYear: string;
    createdAt: bigint;
    publisherId: string;
    publisherName: string;
    isActive: boolean;
}
export interface TrainedServiceMeetingConductor {
    id: string;
    status: string;
    createdAt: bigint;
    publisherId: string;
    publisherName: string;
    trainingDate: bigint;
}
export interface Territory {
    id: string;
    status: string;
    createdAt: bigint;
    checkOutHistory: Array<CheckoutRecord>;
    territoryType: string;
    notes: string;
    number: string;
}
export interface UpdateTrainedConductorInput {
    status: string;
    publisherId: string;
    publisherName: string;
    trainingDate: bigint;
}
export interface CreateTerritoryNoteInput {
    title: string;
    content: string;
}
export interface TerritoryNote {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
}
export interface Publisher {
    id: PublisherId;
    privileges: {
        servant: boolean;
        publisher: boolean;
        elder: boolean;
    };
    fieldServiceGroup: bigint;
    fullName: string;
    isGroupOverseer: boolean;
    isActive: boolean;
    isGroupAssistant: boolean;
}
export interface CreateShepherdingVisitInput {
    eldersPresent: string;
    visitDate: bigint;
    publisherId: string;
    publisherName: string;
    notes: string;
}
export interface CheckoutRecord {
    publisherId: PublisherId;
    publisherName: string;
    dateReturned?: bigint;
    isCampaign: boolean;
    dateCheckedOut: bigint;
}
export interface UserProfile {
    name: string;
}
export interface CreatePioneerInput {
    serviceYear: string;
    publisherId: string;
    publisherName: string;
}
export enum TaskStatus {
    all = "all",
    completed = "completed",
    uncompleted = "uncompleted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPublisher(fullName: string, fieldServiceGroup: bigint, privileges: {
        servant: boolean;
        publisher: boolean;
        elder: boolean;
    }, isGroupOverseer: boolean, isGroupAssistant: boolean, isActive: boolean | null): Promise<PublisherId>;
    addTrainedConductor(input: CreateTrainedConductorInput): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkOutTerritory(territoryId: string, publisherId: PublisherId, isCampaign: boolean): Promise<void>;
    createGlobalNote(title: string, content: string, category: string, attachedPublisher: PublisherId | null): Promise<bigint>;
    createPioneer(input: CreatePioneerInput): Promise<string>;
    createShepherdingVisit(input: CreateShepherdingVisitInput): Promise<string>;
    createTask(input: CreateTaskInput): Promise<bigint>;
    createTerritory(id: string, number: string, territoryType: string, status: string | null, notes: string | null): Promise<string>;
    createTerritoryNote(territoryId: string, input: CreateTerritoryNoteInput): Promise<bigint>;
    deleteGlobalNote(id: bigint): Promise<void>;
    deletePioneer(id: string): Promise<void>;
    deletePublisher(id: PublisherId): Promise<void>;
    deleteShepherdingVisit(id: string): Promise<void>;
    deleteTask(id: bigint): Promise<void>;
    deleteTerritory(id: string): Promise<void>;
    deleteTerritoryNote(territoryId: string, noteId: bigint): Promise<void>;
    deleteTrainedConductor(id: string): Promise<void>;
    editPioneer(id: string, input: EditPioneerInput): Promise<void>;
    getAllGlobalNotes(): Promise<Array<GlobalNote>>;
    getAllPioneers(): Promise<Array<Pioneer>>;
    getAllPublishers(): Promise<Array<Publisher>>;
    getAllServiceMeetingConductors(): Promise<Array<ServiceMeetingConductor>>;
    getAllShepherdingVisits(): Promise<Array<ShepherdingVisit>>;
    getAllTerritories(): Promise<Array<Territory>>;
    getAllTerritoryNotes(territoryId: string): Promise<Array<TerritoryNote>>;
    getAllTrainedConductors(): Promise<Array<TrainedServiceMeetingConductor>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGlobalNote(id: bigint): Promise<GlobalNote | null>;
    getPublisher(id: PublisherId): Promise<Publisher | null>;
    getShepherdingVisit(id: string): Promise<ShepherdingVisit | null>;
    getShepherdingVisitsByPublisher(publisherId: string): Promise<Array<ShepherdingVisit>>;
    getTask(id: bigint): Promise<Task | null>;
    getTasks(status: TaskStatus): Promise<Array<Task>>;
    getTasksByParent(parentTaskId: bigint | null): Promise<Array<Task>>;
    getTerritory(id: string): Promise<Territory | null>;
    getTerritoryNote(territoryId: string, noteId: bigint): Promise<TerritoryNote | null>;
    getTrainedConductor(id: string): Promise<TrainedServiceMeetingConductor | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    makeTerritoryAvailable(territoryId: string): Promise<void>;
    markTerritoryReturned(territoryId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    togglePublisherActiveState(id: PublisherId): Promise<void>;
    updateCheckoutRecord(territoryId: string, originalPublisherId: PublisherId, originalDateCheckedOut: bigint, newPublisherId: PublisherId, newDateCheckedOut: bigint, newDateReturned: bigint | null, newIsCampaign: boolean): Promise<void>;
    updateGlobalNote(id: bigint, title: string, content: string, category: string, attachedPublisher: PublisherId | null): Promise<void>;
    updatePublisher(id: PublisherId, fullName: string, fieldServiceGroup: bigint, privileges: {
        servant: boolean;
        publisher: boolean;
        elder: boolean;
    }, isGroupOverseer: boolean, isGroupAssistant: boolean, isActive: boolean): Promise<void>;
    updateShepherdingVisit(id: string, publisherId: string, publisherName: string, visitDate: bigint, eldersPresent: string, notes: string): Promise<void>;
    updateTask(id: bigint, input: CreateTaskInput): Promise<void>;
    updateTaskCompletion(id: bigint, isCompleted: boolean): Promise<void>;
    updateTerritory(id: string, number: string, territoryType: string): Promise<void>;
    updateTerritoryNote(territoryId: string, noteId: bigint, input: CreateTerritoryNoteInput): Promise<void>;
    updateTrainedConductor(id: string, input: UpdateTrainedConductorInput): Promise<void>;
}
import type { CheckoutRecord as _CheckoutRecord, CreateTaskInput as _CreateTaskInput, GlobalNote as _GlobalNote, Publisher as _Publisher, PublisherId as _PublisherId, ShepherdingVisit as _ShepherdingVisit, Task as _Task, TaskStatus as _TaskStatus, Territory as _Territory, TerritoryNote as _TerritoryNote, TrainedServiceMeetingConductor as _TrainedServiceMeetingConductor, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPublisher(arg0: string, arg1: bigint, arg2: {
        servant: boolean;
        publisher: boolean;
        elder: boolean;
    }, arg3: boolean, arg4: boolean, arg5: boolean | null): Promise<PublisherId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPublisher(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPublisher(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addTrainedConductor(arg0: CreateTrainedConductorInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrainedConductor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrainedConductor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkOutTerritory(arg0: string, arg1: PublisherId, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOutTerritory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOutTerritory(arg0, arg1, arg2);
            return result;
        }
    }
    async createGlobalNote(arg0: string, arg1: string, arg2: string, arg3: PublisherId | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGlobalNote(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGlobalNote(arg0, arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createPioneer(arg0: CreatePioneerInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPioneer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPioneer(arg0);
            return result;
        }
    }
    async createShepherdingVisit(arg0: CreateShepherdingVisitInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createShepherdingVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShepherdingVisit(arg0);
            return result;
        }
    }
    async createTask(arg0: CreateTaskInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_CreateTaskInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_CreateTaskInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTerritory(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTerritory(arg0, arg1, arg2, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTerritory(arg0, arg1, arg2, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createTerritoryNote(arg0: string, arg1: CreateTerritoryNoteInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTerritoryNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTerritoryNote(arg0, arg1);
            return result;
        }
    }
    async deleteGlobalNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGlobalNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGlobalNote(arg0);
            return result;
        }
    }
    async deletePioneer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePioneer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePioneer(arg0);
            return result;
        }
    }
    async deletePublisher(arg0: PublisherId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublisher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublisher(arg0);
            return result;
        }
    }
    async deleteShepherdingVisit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShepherdingVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShepherdingVisit(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteTerritory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTerritory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTerritory(arg0);
            return result;
        }
    }
    async deleteTerritoryNote(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTerritoryNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTerritoryNote(arg0, arg1);
            return result;
        }
    }
    async deleteTrainedConductor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrainedConductor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrainedConductor(arg0);
            return result;
        }
    }
    async editPioneer(arg0: string, arg1: EditPioneerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPioneer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPioneer(arg0, arg1);
            return result;
        }
    }
    async getAllGlobalNotes(): Promise<Array<GlobalNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGlobalNotes();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGlobalNotes();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPioneers(): Promise<Array<Pioneer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPioneers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPioneers();
            return result;
        }
    }
    async getAllPublishers(): Promise<Array<Publisher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishers();
            return result;
        }
    }
    async getAllServiceMeetingConductors(): Promise<Array<ServiceMeetingConductor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceMeetingConductors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceMeetingConductors();
            return result;
        }
    }
    async getAllShepherdingVisits(): Promise<Array<ShepherdingVisit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShepherdingVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShepherdingVisits();
            return result;
        }
    }
    async getAllTerritories(): Promise<Array<Territory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTerritories();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTerritories();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTerritoryNotes(arg0: string): Promise<Array<TerritoryNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTerritoryNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTerritoryNotes(arg0);
            return result;
        }
    }
    async getAllTrainedConductors(): Promise<Array<TrainedServiceMeetingConductor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrainedConductors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrainedConductors();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalNote(arg0: bigint): Promise<GlobalNote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalNote(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalNote(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublisher(arg0: PublisherId): Promise<Publisher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublisher(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublisher(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShepherdingVisit(arg0: string): Promise<ShepherdingVisit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShepherdingVisit(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShepherdingVisit(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShepherdingVisitsByPublisher(arg0: string): Promise<Array<ShepherdingVisit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShepherdingVisitsByPublisher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShepherdingVisitsByPublisher(arg0);
            return result;
        }
    }
    async getTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: TaskStatus): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(to_candid_TaskStatus_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(to_candid_TaskStatus_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByParent(arg0: bigint | null): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByParent(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByParent(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTerritory(arg0: string): Promise<Territory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTerritory(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTerritory(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTerritoryNote(arg0: string, arg1: bigint): Promise<TerritoryNote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTerritoryNote(arg0, arg1);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTerritoryNote(arg0, arg1);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainedConductor(arg0: string): Promise<TrainedServiceMeetingConductor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainedConductor(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainedConductor(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async makeTerritoryAvailable(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.makeTerritoryAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeTerritoryAvailable(arg0);
            return result;
        }
    }
    async markTerritoryReturned(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTerritoryReturned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTerritoryReturned(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async togglePublisherActiveState(arg0: PublisherId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePublisherActiveState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePublisherActiveState(arg0);
            return result;
        }
    }
    async updateCheckoutRecord(arg0: string, arg1: PublisherId, arg2: bigint, arg3: PublisherId, arg4: bigint, arg5: bigint | null, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCheckoutRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCheckoutRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateGlobalNote(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: PublisherId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGlobalNote(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGlobalNote(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updatePublisher(arg0: PublisherId, arg1: string, arg2: bigint, arg3: {
        servant: boolean;
        publisher: boolean;
        elder: boolean;
    }, arg4: boolean, arg5: boolean, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublisher(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublisher(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateShepherdingVisit(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShepherdingVisit(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShepherdingVisit(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: CreateTaskInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_CreateTaskInput_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_CreateTaskInput_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskCompletion(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskCompletion(arg0, arg1);
            return result;
        }
    }
    async updateTerritory(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTerritory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTerritory(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTerritoryNote(arg0: string, arg1: bigint, arg2: CreateTerritoryNoteInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTerritoryNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTerritoryNote(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTrainedConductor(arg0: string, arg1: UpdateTrainedConductorInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrainedConductor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrainedConductor(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CheckoutRecord_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckoutRecord): CheckoutRecord {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_GlobalNote_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlobalNote): GlobalNote {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Territory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Territory): Territory {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublisherId]): PublisherId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GlobalNote]): GlobalNote | null {
    return value.length === 0 ? null : from_candid_GlobalNote_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Publisher]): Publisher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShepherdingVisit]): ShepherdingVisit | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Territory]): Territory | null {
    return value.length === 0 ? null : from_candid_Territory_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TerritoryNote]): TerritoryNote | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrainedServiceMeetingConductor]): TrainedServiceMeetingConductor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    category: string;
    attachedPublisher: [] | [_PublisherId];
}): {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    category: string;
    attachedPublisher?: PublisherId;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        category: value.category,
        attachedPublisher: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.attachedPublisher))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    createdAt: bigint;
    checkOutHistory: Array<_CheckoutRecord>;
    territoryType: string;
    notes: string;
    number: string;
}): {
    id: string;
    status: string;
    createdAt: bigint;
    checkOutHistory: Array<CheckoutRecord>;
    territoryType: string;
    notes: string;
    number: string;
} {
    return {
        id: value.id,
        status: value.status,
        createdAt: value.createdAt,
        checkOutHistory: from_candid_vec_n15(_uploadFile, _downloadFile, value.checkOutHistory),
        territoryType: value.territoryType,
        notes: value.notes,
        number: value.number
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publisherId: _PublisherId;
    publisherName: string;
    dateReturned: [] | [bigint];
    isCampaign: boolean;
    dateCheckedOut: bigint;
}): {
    publisherId: PublisherId;
    publisherName: string;
    dateReturned?: bigint;
    isCampaign: boolean;
    dateCheckedOut: bigint;
} {
    return {
        publisherId: value.publisherId,
        publisherName: value.publisherName,
        dateReturned: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.dateReturned)),
        isCampaign: value.isCampaign,
        dateCheckedOut: value.dateCheckedOut
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completedAt: [] | [bigint];
    title: string;
    isCompleted: boolean;
    createdAt: bigint;
    dueDate: bigint;
    updatedAt: [] | [bigint];
    parentTaskId: [] | [bigint];
    notes: [] | [string];
    category: string;
}): {
    id: bigint;
    completedAt?: bigint;
    title: string;
    isCompleted: boolean;
    createdAt: bigint;
    dueDate: bigint;
    updatedAt?: bigint;
    parentTaskId?: bigint;
    notes?: string;
    category: string;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.completedAt)),
        title: value.title,
        isCompleted: value.isCompleted,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        updatedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.updatedAt)),
        parentTaskId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.parentTaskId)),
        notes: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.notes)),
        category: value.category
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Territory>): Array<Territory> {
    return value.map((x)=>from_candid_Territory_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CheckoutRecord>): Array<CheckoutRecord> {
    return value.map((x)=>from_candid_CheckoutRecord_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GlobalNote>): Array<GlobalNote> {
    return value.map((x)=>from_candid_GlobalNote_n9(_uploadFile, _downloadFile, x));
}
function to_candid_CreateTaskInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTaskInput): _CreateTaskInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublisherId | null): [] | [_PublisherId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    dueDate: bigint;
    parentTaskId?: bigint;
    notes?: string;
    category: string;
}): {
    title: string;
    dueDate: bigint;
    parentTaskId: [] | [bigint];
    notes: [] | [string];
    category: string;
} {
    return {
        title: value.title,
        dueDate: value.dueDate,
        parentTaskId: value.parentTaskId ? candid_some(value.parentTaskId) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: value.category
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    all: null;
} | {
    completed: null;
} | {
    uncompleted: null;
} {
    return value == TaskStatus.all ? {
        all: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.uncompleted ? {
        uncompleted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
